### PR TITLE
fix: bare enums serialize with their tags

### LINKED ISSUE #738: `ResultKind` and `ResultLevel` appear to serialize incorrectly
Hi there! First of all, thanks for this library -- it's been fantastic to use.

I'm trying to emit some well-formed SARIF in [zizmor](https://github.com/woodruffw/zizmor) and I'm running into some weirdness with how `ResultLevel` and `ResultKind` are serialized. More precisely, they seem to always be serialized as `null` (i.e. `serde_json::value::Value::Null`), regardless of their actual value.

Here's a minimal failing reproducer:

```rust
#[cfg(test)]
mod tests {
    use serde_sarif::sarif::ResultKind;

    #[test]
    fn test_resultkind_serializes() {
        assert_eq!(
            serde_json::to_string(&ResultKind::Fail).unwrap(),
            "\"fail\""
        );
    }
}
```

The expected behavior is that this serializes to the JSON string `"fail"`, but instead it serializes as `null`:

```console
assertion `left == right` failed
  left: "null"
 right: "\"fail\""
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I took a quick look at the code, and it doesn't _look_ wrong, but I'm not super familiar with `strum` (which seems to be controlling the serialization equivalents for each enum variant).

Let me know if there's any other information I can provide! I'll also keep debugging this on my end.

### PR DESCRIPTION
**Pull request by woodruffw**
This should fix #738: enums that were previously marked as `serde(untagged)` are now marked with `#[serde(rename_all = "camelCase")]` where appropriate, causing them to serialize as their expected camelCase string equivalents.

I've also gone and deduplicated `#[strum(serialize = "...")]` where possible, by moving all of the explicit camelCasing to `#[strum(serialize_all = "camelCase")]`.

### CODE REVIEW

**Comment by psastras** [comment]
@woodruffw thanks for the issue report and PR, I'll try to take a look later this week!

**Comment by woodruffw** [comment]
Gentle ping for review on this! 🙂

**Comment by woodruffw** [comment]
@psastras another gentle ping for review here :slightly_smiling_face: -- this is a blocker for some improvements I want to land in [`zizmor`](https://github.com/woodruffw/zizmor), so I'd greatly appreciate a fix here!

Please let me know if there's anything I can do to make review easy/painless here.

**Review by psastras — APPROVED** [review]

**Comment by psastras** [comment]
@woodruffw sorry looks good and again thank you -- i've rebased and move this here https://github.com/psastras/sarif-rs/pull/767 will merge and release

**Comment by psastras** [comment]
will close this pr but feel free to re-open discussion if needed!

**Comment by psastras** [comment]
@woodruffw this is available on crates.io https://crates.io/crates/serde-sarif thanks for you work!

**Comment by woodruffw** [comment]
Thanks @psastras, I greatly appreciate it! I'll have some follow-up PRs, but this was the big blocker for me 🙂

**Pull request closed without merging**
