### PR TITLE
Extend `clippy-sarif` to re-emit the original formatted error messages

### PR DESCRIPTION
**Pull request by jonasbb**
I tried implementing my suggestion from https://github.com/psastras/sarif-rs/discussions/171

The code adds a new flag to `clippy-sarif` which prints the original rendered diagnostics if they are available in the JSON messages.
The handling looks a bit ugly due to the multiple necessary checks. For one, messages need to be deduplicated, as the same warning can appear for different targets, e.g., lib+docs.
The same message can also appear for different targets, which is why the whole `CompilerMessage` is deduplicated, not just the rendered diagnostic.
The one additional `Result` layer for the `filter_map` is necessary, to correctly handle errors when writing to stderr, for example if it is redirected to `/dev/full`.

I would be happy to hear some feedback if this is an acceptable way to implement the feature.

---

clippy original error message:

```
warning: unused variable: `x`
   --> clippy-sarif/src/bin.rs:120:7
    |
120 |   let x = ();
    |       ^ help: if this is intentional, prefix it with an underscore: `_x`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: `clippy-sarif` (bin "clippy-sarif" test) generated 1 warning
warning: `clippy-sarif` (bin "clippy-sarif") generated 1 warning (1 duplicate)
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
```

`cargo clippy --all-targets --all-features --message-format=json-diagnostic-rendered-ansi 2>/dev/null | clippy-sarif --emit-rendered-diagnostics >./results.sarif`:

```
warning: unused variable: `x`
   --> clippy-sarif/src/bin.rs:120:7
    |
120 |   let x = ();
    |       ^ help: if this is intentional, prefix it with an underscore: `_x`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted
```

### CODE REVIEW

**Comment by psastras** [comment]
hey thanks for submitting this -- some thoughts:

I'm not sure if we want to open up stderr in `process` since this is also published as a crate and people _should_ be able to pull this in as a dependency if they want to write their own tool to convert from json -> sarif, and I don't think we want to print out to stderr in a library function.

I think what feels like the cleanest way to me, would be to see if we can output the original diagnostic in a SARIF field (maybe using the properties bag?) - and then have `sarif-fmt` interpret that field properly (maybe via a new cli flag like you added).

wdyt?

**Comment by jonasbb** [comment]
> I'm not sure if we want to open up stderr in `process` since this is also published as a crate and people _should_ be able to pull this in as a dependency if they want to write their own tool to convert from json -> sarif, and I don't think we want to print out to stderr in a library function.

That is absolutely fair.

> I think what feels like the cleanest way to me, would be to see if we can output the original diagnostic in a SARIF field (maybe using the properties bag?) - and then have `sarif-fmt` interpret that field properly (maybe via a new cli flag like you added).

Storing the diagnostics in the SARIF file feels unnecessary. I am not really interested in storing them or keeping them long term. It will also make the file upload slower. It has the advantage of being clean in that it doesn't touch the return type of functions.

I think changing the return type of `process` might be an alternative. This also needs to affect the `parse_to_*` functions. I would change the type to something like `Result<(sarif::Sarif, Option<Vec<String>>)>`. For readability as a struct and maybe a newtype around `String`. It would be `Some` if `emitted_rendered_diagnostics` is true and each entry would be the diagnostic in the order they were emitted.

**Comment by psastras** [comment]
Hmm, changing the return output seems ok to me...Would like to think about what a nice return structure would look like,

```
Result<(sarif::Sarif, Option<Vec<String>>)>
```

doesn't really explain what Vec<String> should be to me -- is it just stderr, could process add other strings to the vec (and hypothetically what if we add another flag that process needs to print info for?

What do you think about having something like `process(reader, stdout: Option<Writer>, stderr: Option<Writer>)`?

**Comment by jonasbb** [comment]
My idea with the extra return arguments was that the caller can decide what to do with the extra information. If you use it as part of another library you might just want to ignore it. The CLI tool can decide if it should be printed and if so, if it should go to stdout, stderr, or a file. New outputs would become further fields and process would only set them.

I think a struct design like this is explanatory enough:
```rust
// Main return value
Result<ProcessedClippySarif>

struct ProcessedClippySarif {
    sarif: sarif::
    diagnostics: Option<Vec<Diagnostic>>,
    // alternative:
    // diagnostics: Option<Diagnostics>,
}

struct Diagnostic(String);

struct Diagnostics(Vec<Diagnostic>);
```

> What do you think about having something like `process(reader, stdout: Option<Writer>, stderr: Option<Writer>)`?

That design has no information what `stdout` and `stderr` are being used for. Right now, diagnostics would be the only use case, so one output stream would always be unused. Only providing a `Writer` also looses any structure which did exist before

**Comment by psastras** [comment]
@jonasbb i like the look of your proposed `ProcessedClippySarif` struct, lgtme.

it's a little annoying (im) that the different `process` functions for types have slightly different signatures, but not the end of the world

**Pull request closed without merging**
