### PR TITLE
Fix bug compiling using 1.53

### PR DESCRIPTION
**Pull request by GeekMasher**
- Update to 1.54.0
- Changed clip about() to help()

**Issue:**

- https://github.com/psastras/sarif-rs/issues/104

### CODE REVIEW

**Comment by yongyan-gh** [comment]
Other components in this repo (clang-tidy-sarif/hadolint-sarif/sarif-fmt etc.) have the same compiling issue. Will you fix all of them?

**Comment by psastras** [comment]
@yongyan-gh thanks for the contribution. and sorry for the slow reply -- I was mostly away from the computer over the holidays.

I'll take a look at the other issues.

**Comment by psastras** [comment]
hi - i've update the code to support 1.58.0 which should solve the compiling issue. unfortunately, CI is a little broken so fixing. once that's done it should be released with a new version. ill let you know once that happens. if there are any issues please feel free to re-open

**Comment by psastras** [comment]
fyi, an updated build has been released. thanks @GeekMasher for finding the core build problem

**Pull request closed without merging**
