### PR TITLE
Breaking: Use `TypedBuilder`, update URL to final release

### PR DESCRIPTION
**Pull request by jssblck**
Hello! Thanks for taking the time to make this library, it's really awesome!

When using it, I found it really unwieldy to use due to the runtime checked builder pattern.
I also noted that the spec URL is out of date (although the data generated appears to be in line with the current spec).

This PR:
- Replaces `derive_builder::Builder` with `typed_builder::TypedBuilder`.
- Updates most previously fallible conversions to be infallible:
  - e.g. `impl TryFrom<&cargo_metadata::diagnostic::Diagnostic> for sarif::Message`
  - is now `impl From<&Diagnostic> for sarif::Message`
- Updates `serde_sarif::sarif::SCHEMA_URL` to `sarif-2.1.0.json`.
- Does a couple minor cleanups I noticed along the way.
  - If I misunderstood and any of these aren't cleanups (especially the `profraw` files), happy to revert those changes, just let me know.

I believe the changes make the project easier to use and improve the experience in the IDE, as IMO `TypedBuilder` has subjectively better diagnostics and autocompletion than `Builder`.

I bumped the project with a breaking change, and bumped the versions of each binary in the workspace with minor version bumps (since I think their interface doesn't change). Let me know if you want them to be bumped with a breaking change instead (and obviously feel free to make any changes before merging to your project).

I made these changes for us at my company, but wanted to go ahead and upstream them if you're interested. If not, totally understandable, just let me know!

Thanks for your time!

### CODE REVIEW

**Comment by psastras** [comment]
@jssblck Hello, thanks for the PR -- at a quick glance I think the direction generally looks good and appreciate some of the cleanup you've done, I'll find some time later this week to review it (and hopefully get it merged if all looks good)!

**Review by psastras — CHANGES_REQUESTED** [review]
hey, I've taken a look and the changes all look good to me.

before merging, could I ask you to clean up the git history? the granularity is generally fine, but would appreciate rewriting the titles to follow conventional commits.

**Comment by jssblck** [comment]
> hey, I've taken a look and the changes all look good to me.
> 
> before merging, could I ask you to clean up the git history? the granularity is generally fine, but would appreciate rewriting the titles to follow conventional commits.

I've always just done squash merges, what do you mean by "conventional commits"?

**Comment by jssblck** [comment]
> hey, I've taken a look and the changes all look good to me.
> 
> before merging, could I ask you to clean up the git history? the granularity is generally fine, but would appreciate rewriting the titles to follow conventional commits.

@psastras I've always just done squash merges, what do you mean by "conventional commits"?

**Comment by psastras** [comment]
@jssblck ah, yeah I don't allow squash merges here which requires cleanup on the PR, yes thats the correct link.

I think the easiest way is, if you want to squash: `git rebase -i HEAD~3` (replace 3 with however many commits in your stack) then edit the commit title to something like `feat!: use TypedBuilder instead of Builder`.

But anyway you want to work it out so that the commit titles follow that format would be really helpful.

**Comment by jssblck** [comment]
@psastras done, I believe! Also fixed merge conflicts.

**Review by psastras — APPROVED** [review]

**Comment by psastras** [comment]
@jssblck thanks, ill merge it and get i published to crates.io!

**Pull request merged**
