### PR TITLE
support cargo-binstall

### PR DESCRIPTION
**Pull request by fgardt**
This additional metadata should add support for [cargo-binstall](https://github.com/cargo-bins/cargo-binstall).
Using `cargo binstall [crate]` instead of `cargo install crate` allows for faster installs since we can just download the binaries.
This helps reduce CI run time if a crate is not cached.

### Example workflow
```yml
on: [pull_request]

jobs:
clippy:
    name: Clippy
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@v1
      - name: Install cargo-binstall
        run: wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-gnu.tgz -O - | tar -xz -C $HOME/.cargo/bin  
      - run: cargo binstall sarif-fmt clippy-sarif && chmod +x -R $HOME/.cargo/bin
      - run: cargo clippy --all-targets --all-features --message-format=json |
          clippy-sarif | tee results.sarif | sarif-fmt
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
```

_**note:** for some reason the release artifacts don't have the +x attribute. Is this a limitation of GitHub since the binaries are not packed in an archive?_

### CODE REVIEW

**Comment by fgardt** [comment]
A workaround while this is not supported is
```bash
cargo binstall \                                                                                                                                                                     ✔ 
               --pkg-url="{ repo }/releases/download/{ name }-v{ version }/{ name }-{ target }" \
               --pkg-fmt="bin" clippy-sarif
```
but this only allows to install 1 crate at a time and you need to run `chmod +x -R $HOME/.cargo/bin` to make the binaries executable

**Comment by psastras** [comment]
> note: for some reason the release artifacts don't have the +x attribute. Is this a limitation of GitHub since the binaries are not packed in an archive?

basically yes, permissions are not attached to a file, they are stored file attributes stored separately (the storage mechanism depends on the OS/filesystem).

the reason it works for archives, is because archivers like tar have additional logic to allow storing file attributes and restoring them once un archived on the target system.

**Comment by psastras** [comment]
@fgardt thanks for the PR, basically it lgtme to merge, although maybe add a blurb in README.md about this?


ex:

```
### Cargo

```shell
cargo install <cli_name> # ex. cargo install sarif-fmt
```
#### Cargo Bin Install
...

```

**Review by psastras — APPROVED** [review]

**Comment by fgardt** [comment]
sure I can add a bit about it to the README

**Comment by fgardt** [comment]
also opened an issue at `cargo-binstall` about the file permission issue
https://github.com/cargo-bins/cargo-binstall/issues/406

**Review by psastras — APPROVED** [review]

**Comment by psastras** [comment]
reapproved thanks!

unfortunately looks like clippy got an update and is failing on an unrelated part of the code. ill fix it over the weekend and merge this once I do.

**Pull request merged**
