### PR TITLE
feat: add --color option (useful in CI/CD environments)

### PR DESCRIPTION
**Pull request by L11R**
In CI/CD environments like GitLab CI, termcolor library cannot determine tty and fallbacks to no color at all. This option allows to force color in such environments. Tested with GitLab CI, now out outputs colorful :)

### CODE REVIEW

**Comment by TheJokr** [comment]
I solved the same problem in my GitHub workflows by setting `TERM=xterm-256color`, but that is obviously quite hacky. I'd love to have a flag for this, but I think `--color {auto | always | never}` (as used in `cargo`, for example) would make for a less surprising interface than the `--always-ansi` boolean.

`--color always` could then map to `AlwaysAnsi` for maximum compatibility.

**Comment by L11R** [comment]
@TheJokr nice suggestion! Now it should be better.

**Comment by L11R** [comment]
@psastras can you review it?

**Comment by psastras** [comment]
@L11R thanks, this change lgtme, I'll get it merged and released

**Comment by psastras** [comment]
this should be available in 0.4.0

**Pull request merged**
